USE ROLE TRAINING_ROLE;
USE WAREHOUSE MONKEY_WH;
USE DATABASE MONKEY_DB;
USE SCHEMA FINAL_PROJECT;

-- Unified realtime + legacy reporting object smoke checks.

SHOW DYNAMIC TABLES LIKE 'DT_REALTIME_ARTICLE_COMPANY_MATCH' IN SCHEMA MONKEY_DB.FINAL_PROJECT;
SHOW DYNAMIC TABLES LIKE 'DT_UNIFIED_ARTICLE_COMPANY_MENTIONS' IN SCHEMA MONKEY_DB.FINAL_PROJECT;
SHOW DYNAMIC TABLES LIKE 'RPT_COMPANY_ARTICLE_VOLUME' IN SCHEMA MONKEY_DB.FINAL_PROJECT;
SHOW DYNAMIC TABLES LIKE 'RPT_COMPANY_SENTIMENT_SUMMARY' IN SCHEMA MONKEY_DB.FINAL_PROJECT;
SHOW DYNAMIC TABLES LIKE 'RPT_DAILY_TREND' IN SCHEMA MONKEY_DB.FINAL_PROJECT;
SHOW DYNAMIC TABLES LIKE 'RPT_SENTIMENT_EXAMPLES' IN SCHEMA MONKEY_DB.FINAL_PROJECT;
SHOW DYNAMIC TABLES LIKE 'RPT_TOP_SOURCES' IN SCHEMA MONKEY_DB.FINAL_PROJECT;

SELECT COUNT(*) AS unified_rows FROM dt_unified_article_company_mentions;
SELECT provider, COUNT(*) AS cnt
FROM dt_unified_article_company_mentions
GROUP BY 1
ORDER BY cnt DESC;
