USE ROLE TRAINING_ROLE;
USE WAREHOUSE MONKEY_WH;
USE DATABASE MONKEY_DB;
USE SCHEMA FINAL_PROJECT;

SELECT
  name,
  scheduling_state,
  last_refresh_time,
  rows
FROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY(
  NAME_PREFIX => 'RPT_',
  RESULT_LIMIT => 50
))
ORDER BY last_refresh_time DESC;
